export default {
  'TAN': 'tan(x)返回给定角度x的正切值',
  'LN': 'ln(x)返回给定数值x的自然对数',
  'RAND': '生成随机数',
  'SQRT': 'sqrt(x)返回数值x的平方根',
  'MLTIDIMENSION': '基础数据映射解析器，前面的参数不允许修改，后面可以根据映射表的设置分别放置变量或常量。',
  'TOUPPERCASE': 'toUpperCase(String st) 求字符串st的大写形式',
  'GLCASHFLOW': '拼接查询条件！',
  'ANGLE': 'Math.atan2(x.doubleValue(), y.doubleValue())',
  'AUXILIARY': '基础数据映射解析器，前面的参数不允许修改，后面可以根据映射表的设置分别放置变量或常量。',
  'LASTINDEXOF': 'lastIndexOf(st1, st2) 判断字符串st1中最后一个字符串st2所在的位置,比如lastIndexOf(\'HI,UAP2006,UAP\',\'UAP\')返回11.',
  'GETACCOUNTBALANCE': '拼接查询条件！',
  'ATANH': 'atanh(z)  =  1/2 * log( (1+z)/(1-z) )',
  'INDEXOF': 'indexOf(st1, st2) 判断字符串st1中第一个字符串st2所在的位置,比如lastIndexOf(\'HI,UAP2006,UAP\',\'UAP\')返回3.',
  'ACOS': 'acos(x)返回一个弧度x的反余弦,弧度值在0到Pi之间',
  'RIGHTSTR': 'rightStr(st,len,defaultStr) 求字符串st右边后len个字符组成的字符串，如果字符串长度小于len，则用defaultStr补齐,比如rightStr(\'abc\',6,\'@\')将返回abc@@@.',
  'TOSTRING': 'toString(obj) 将对象obj转换为本解析器可识别的字符串形式',
  'IF': 'iif(condition, result1, result2)',
  'LEFT': 'left(st, index) 求字符串st左边前index个字符组成的字符串',
  'ENDSWITH': 'endswith(st, end)判断字符串st是否以字符串end结尾',
  'LOG': 'log(x)返回给定数n的以十为底的对数',
  'IIF': 'iif(condition, result1, result2)',
  'GETFIELDVALUE': '得到指定字段的值！',
  'MID': 'mid(String st, int start, int end) 求字符串st左边前第start个字符至第end个字符之间的字符串',
  'SUM': '计算两个数的和',
  'CMAPPING': '基础数据映射解析器，前面的参数不允许修改，后面可以根据映射表的设置分别放置变量或常量。',
  'ACOSH': 'acosh(z)  =  log(z + sqrt(z*z - 1))',
  'MIN': 'min(x, y) 求x,y两者中的最小值',
  'LEFTSTR': 'leftStr(st,len,defaultStr) 求字符串st左边前len个字符组成的字符串，如果字符串长度小于len，则用defaultStr补齐,比如leftStr(\'abc\',6,\'@\')将返回abc@@@.',
  'GETDOCDATA': '得到首个档案对象！',
  'SINH': 'sinh(z)  =  ( exp(z) - exp(-z) ) / 2',
  'SIN': 'sin(x)返回给定角度x的正弦值',
  'CONDITION': '拼接查询条件！',
  'COND': '拼接查询条件！',
  'ATAN': 'atan(x)返回一个弧度x的反正切值,弧度值在-Pi/2到Pi/2之间',
  'TANH': 'sinh(z) / cosh(z)',
  'MAX': 'max(x, y) 求数字x,y两者中的最大值',
  'ROUND': 'round(double num, int index) 对num保留index位小数(四舍五入)',
  'LENGTH': 'length(st) 求字符串st的长度',
  'ASIN': 'asin(x)返回一个弧度x的反正弦,弧度值在-Pi/2到Pi/2之间',
  'GETRESULT': '计算两个数的和',
  'ZEROIFNULL': 'zeroifnull(var)表示如果var为空将返回0',
  'INT': 'int(数字或者字符串) 将变量转换为int类型',
  'TRIMZERO': 'trimzero()剪除字符串或数字str的末尾0值',
  'ABS': 'abs(num)求数num的绝对值',
  'STARTSWITH': 'startsWith(String st, String start) 判断字符串st是否以字符串start开头',
  'TOLOWERCASE': 'toLowerCase(String st) 求字符串st的小写形式,比如toLowerCase(\'Abc\')返回\'abc\'.',
  'GETID': '取档案的ID。',
  'RIGHT': 'right(String st, int index) 求字符串st右边前index个字符组成的字符串',
  'COSH': 'cosh(z)  =  ( exp(z) + exp(-z) ) / 2',
  'TONUMBER': 'toNumber(String st) 将字符串st转换为本解析器可识别的数字,比如toNumber(\'45.0\')将返回一个数字型45.0,经过转化后可参与各种数值计算.',
  'DATEFORMAT': '日期函数，用于处理日期。可以接受0、1、2个参数，无参数时取当前日期，第一个参数可以传入日期值，接受Long、Date以及String，为空取当前日期，第二个参数传入日期格式，例如 yyyy-MM-dd',
  'TRANSCURRENCY': '按汇率转换金额。（参数：汇率方案、业务日期、源币种、目标币种、源币种金额；返回：目标币种金额）',
  'MOD': '求模运算',
  'CHARAT': 'charat(st,index)得到字符串st中第index个字符',
  'COS': 'cos(x)返回给定角度x的余弦值',
  'ASINH': 'asinh(z)  =  log(z + sqrt(z*z + 1))',
  'GLDIFFOFVOUCH': 'description of function',
  'DIV': 'UPPformulaparse-V60000003',
  'GETACCTRUSTRELATIONSHIP': '根据核算委托关系计算目标主体。参数1：核算目的，参数2：委托类型，参数3：委托主体。',
  'GETACCSUBJECT': '根据科目编码，组织查找会计科目！',
  'ISEMPTY': 'isEmpty(变量)用于判断变量是否为空,包括空串(\'\')及空值(null)',
  'GETACCBOOKBYORG': '根据核算组织参数查找有效账簿！',
  'SGN': 'sgn(num) 当数num大于0时,返回1,等于0时,返回0,小于0时返回-1',
  'EXP': 'exp(x)e的x次方'
}